### PR TITLE
Some suggestions

### PR DESCRIPTION
**Pull request by lkubb**
~~Currently scanning the list, will mark this as ready when finished.~~ Finished, these are the most prominent things I noticed.

Some suggestions are for likely mistakes (like `slsutil` in community), some might very well be intended (please correct me in that case).

Edit:
For some, I was unsure what to make of them. Examples:

* The `etcd` modules are distributed over all three categories.
* The `plist` serializer should be part of a MacOS extension imho.
* The `npm` execution module is core-ext, but the state module `core`. Not sure where it should go.

### CODE REVIEW

**Comment by dwoz** [comment]
@lkubb 
- As for npm, I think that should go to core extension. 
- I do not think the yamlex rendered belongs in core.

@whytewolf @twangboy Thoughts?

**Comment by twangboy** [comment]
If we're gonna keep the yamlex serializer, we should keep the yamlex renderer... or visaversa

**Comment by whytewolf** [comment]
personally. I'm more partial to `npm` being moved to community. but then again that could because of a hate of nodejs i have. so have a biased opinion. though which ever way it goes the state and the module should go in the same place.

and yeah `yamlex` renderer doesn't belong in core. though the serializer shouldn't be there either. 

I think `chocolaty` would get better support as a community module.

**Comment by twangboy** [comment]
The chocolatey module should go wherever the Windows modules go

**Comment by lkubb** [comment]
So, should I put both `yamlex` modules into community then? Ftr, I think the `!aggregate` tag is neat functionality to avoid bloated top files, don't care about the rest. Would it be an option to add it to the regular YAML renderer?

Agree that Windows and Mac-related modules should go into the same extension, wherever the team deems fit. As mentioned, I would include the `plist` serializer in the Mac-related modules.

Also agree `npm` should either be community or core ext, probably even the former.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
